/*
 * Copyright (C) 2023 thevalidator
 */
package ru.thevalidator.snake.gui;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.JLabel;
import static ru.thevalidator.snake.gui.GamePanel.BOARD_SIZE;

/**
 *
 * @author thevalidator <the.validator@yandex.ru>
 */
public class InfoPanel extends javax.swing.JPanel {
    
    public static final int INFO_BLOCK_SIZE = 50;
    private final Dimension dimension;

    /**
     * Creates new form InfoPanel
     */
    public InfoPanel() {
        dimension = new java.awt.Dimension(BOARD_SIZE, INFO_BLOCK_SIZE);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setMaximumSize(dimension);
        setMinimumSize(dimension);
        setPreferredSize(dimension);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
